const fs = require('fs');

const factories = JSON.parse(fs.readFileSync('parsed_factories.json', 'utf-8'));

const deDict = {
  // Goods
  "Helium": "Helium",
  "Hydrogen": "Wasserstoff",
  "Neon": "Neon",
  "Chlorine": "Chlor",
  "Crystals": "Kristalle",
  "Minerals": "Mineralien",
  "Scrap Metal": "Altmetall",
  "Raw Oil": "Rohöl",
  "Oil": "Öl",
  "Energy Cells": "Energiezellen",
  "Energy Cell": "Energiezelle",
  "Corn": "Mais",
  "Carbon": "Kohlenstoff",
  "Steel": "Stahl",
  "Copper": "Kupfer",
  "Conductors": "Leiter",
  "Conductor": "Leiter",
  "Transformators": "Transformatoren",
  "Transformator": "Transformator",
  "Electro Magnets": "Elektromagnete",
  "Electro Magnet": "Elektromagnet",
  "Energy Tube": "Energieröhre",
  "Energy Tubes": "Energieröhren",
  "Energy Inverters": "Energie-Inverter",
  "Energy Inverter": "Energie-Inverter",
  "Aluminum": "Aluminium",
  "Plastic": "Plastik",
  "Servos": "Servos",
  "Steel Tubes": "Stahlröhren",
  "Steel Tube": "Stahlröhre",
  "Rubber": "Gummi",
  "Toxic Waste": "Giftmüll",
  "Acid": "Säure",
  "Zinc": "Zink",
  "Platinum": "Platin",
  "Gold": "Gold",
  "Silver": "Silber",
  "Silicon": "Silizium",
  "Solar Cells": "Solarzellen",
  "Tools": "Werkzeuge",
  "Semi Conductors": "Halbleiter",
  "Wires": "Kabel",
  "Microchips": "Mikrochips",
  "Microchip": "Mikrochip",
  "Ore": "Erz",
  "Coal": "Kohle",
  "Bio Gas": "Biogas",
  "Plasma Cells": "Plasmazellen",
  "Plasma Cell": "Plasmazelle",
  "Nitrogen": "Stickstoff",
  "Fluorine": "Fluor",
  "Fuel": "Treibstoff",
  "Glass": "Glas",
  "Water": "Wasser",
  "Oxygen": "Sauerstoff",
  "Chemicals": "Chemikalien",
  "Adhesive": "Klebstoff",
  "Coolant": "Kühlmittel",
  "Solvent": "Lösungsmittel",
  "Metal Plates": "Metallplatten",
  "Metal Plate": "Metallplatte",
  "Paint": "Farbe",
  "Fertilizer": "Dünger",
  "Explosive Charges": "Sprengladungen",
  "Fusion Cores": "Fusionskerne",
  "High Pressure Tubes": "Hochdruckröhren",
  "High Pressure Tube": "Hochdruckröhre",
  "Processors": "Prozessoren",
  "Processor": "Prozessor",
  "Targeting Cards": "Zielkarten",
  "Targeting Card": "Zielkarte",
  "Energy Containers": "Energiecontainer",
  "Energy Container": "Energiecontainer",
  "Electromagnetic Charges": "Elektromagnetische Ladungen",
  "Gauss Rail": "Gauß-Schienen",
  "Energy Generator": "Energiegenerator",
  "Energy Generators": "Energiegeneratoren",
  "Display": "Display",
  "Displays": "Displays",
  "Nanobots": "Nanobots",
  "Laser Compressor": "Laser-Kompressor",
  "Laser Head": "Laserkopf",
  "Drone": "Drohne",
  "Warhead": "Sprengkopf",
  "Power Units": "Leistungseinheiten",
  "Power Unit": "Leistungseinheit",
  "Antigrav Unit": "Antigrav-Einheit",
  "Antigrav Units": "Antigrav-Einheiten",
  "Solar Panel": "Solarpanel",
  "Solar Panels": "Solarpanels",
  "Turbines": "Turbinen",
  "Turbine": "Turbine",
  "Fusion Generators": "Fusionsgeneratoren",
  "Fusion Generator": "Fusionsgenerator",
  "Neutron Accelerator": "Neutronenbeschleuniger",
  "Proton Accelerator": "Protonenbeschleuniger",
  "Electron Accelerator": "Elektronenbeschleuniger",
  "Targeting System": "Zielsystem",
  "Lead": "Blei",
  "Ammunition S": "Munition S",
  "Ammunition M": "Munition M",
  "Ammunition L": "Munition L",
  "Diamonds": "Diamanten",
  "High Capacity Lens": "Hochkapazitätslinse",
  "Laser Modulator": "Lasermodulator",
  "Force Generator": "Kraftfeldgenerator",
  "Antigrav Generator": "Antigrav-Generator",
  "Military Tesla Coil": "Militärische Teslaspule",
  "Industrial Tesla Coil": "Industrielle Teslaspule",
  "Fabric": "Stoff",
  "Medical Supplies": "Medizinische Güter",
  "Satellite": "Satellit",
  "Drill": "Bohrer",
  "Teleporter": "Teleporter",
  "Meat": "Fleisch",
  "Wheat": "Weizen",
  "Cocoa": "Kakao",
  "Coffee Beans": "Kaffeebohnen",
  "Tea": "Tee",
  "Spices": "Gewürze",
  "Potato": "Kartoffel",
  "Vegetables": "Gemüse",
  "Fruit": "Obst",
  "Rice": "Reis",
  "Sheep": "Schaf",
  "Cattle": "Rind",
  "Fish": "Fisch",
  "Milk": "Milch",
  "Beer": "Bier",
  "Wine": "Wein",
  "Liquor": "Spirituosen",
  "Nutrient Extract": "Nährstoffextrakt",
  "Food Bar": "Nahrungsriegel",
  "Luxury Food": "Luxusnahrung",
  "O2": "O2",
  "Potatoes": "Kartoffeln",

  // Factories
  "Gas Collector": "Gassammler",
  "Crystal Farm": "Kristallfarm",
  "Mineral Extractor": "Mineralienextraktor",
  "Scrap Metal Trader": "Altmetallhändler",
  "Oil Refinery": "Ölraffinerie",
  "Solar Power Plant": "Solarkraftwerk",
  "Carbon Extractor": "Kohlenstoffextraktor",
  "Electro Magnet Factory": "Elektromagnet-Fabrik",
  "Energy Inverter Factory": "Energie-Inverter-Fabrik",
  "Servo Factory": "Servo-Fabrik",
  "Steel Tube Factory": "Stahlröhren-Fabrik",
  "Rubber Factory": "Gummifabrik",
  "Conductor Factory": "Leiter-Fabrik",
  "Transformator Factory": "Transformator-Fabrik",
  "Plastic Manufacturer": "Plastikhersteller",
  "Solar Cell Factory": "Solarzellen-Fabrik",
  "Tools Factory": "Werkzeug-Fabrik",
  "Semi Conductor Manufacturer": "Halbleiterhersteller",
  "Microchip Factory": "Mikrochip-Fabrik",
  "Energy Tube Factory": "Energieröhren-Fabrik",
  "Steel Factory": "Stahlfabrik",
  "Plasma Cell Factory": "Plasmazellen-Fabrik",
  "Fuel Factory": "Treibstofffabrik",
  "Glass Manufacturer": "Glashersteller",
  "Chemical Factory": "Chemiefabrik",
  "Wire Manufacturer": "Kabelhersteller",
  "Metal Plate Factory": "Metallplatten-Fabrik",
  "Paint Manufacturer": "Farbenhersteller",
  "Fertilizer Factory": "Düngerfabrik",
  "Explosive Charge Factory": "Sprengladungs-Fabrik",
  "Fusion Core Factory": "Fusionskern-Fabrik",
  "High Pressure Tube Factory": "Hochdruckröhren-Fabrik",
  "Targeting Card Factory": "Zielkarten-Fabrik",
  "Electromagnetic Charge Factory": "Elektromag. Ladungsfabrik",
  "Gauss Rail Factory": "Gauß-Schienen-Fabrik",
  "Energy Generator Factory": "Energiegenerator-Fabrik",
  "Display Factory": "Display-Fabrik",
  "Processor Factory": "Prozessor-Fabrik",
  "Computer Component Factory": "Computerkomponenten-Fabrik",
  "Nanobot Factory": "Nanobot-Fabrik",
  "Laser Compressor Factory": "Laser-Kompressor-Fabrik",
  "Laser Head Factory": "Laserkopf-Fabrik",
  "Drone Factory": "Drohnenfabrik",
  "Warhead Factory": "Sprengkopf-Fabrik",
  "Power Unit Factory": "Leistungseinheit-Fabrik",
  "Antigrav Unit Factory": "Antigrav-Einheit-Fabrik",
  "Energy Container Factory": "Energiecontainer-Fabrik",
  "Solar Panel Factory": "Solarpanel-Fabrik",
  "Accelerator Factory": "Beschleuniger-Fabrik",
  "Targeting System Factory": "Zielsystem-Fabrik",
  "Ammunition Factory": "Munitionsfabrik",
  "High Capacity Lens Factory": "Hochkapazitätslinsen-Fabrik",
  "Laser Modulator Factory": "Lasermodulator-Fabrik",
  "Force Generator Factory": "Kraftfeldgenerator-Fabrik",
  "Antigrav Generator Factory": "Antigrav-Generator-Fabrik",
  "Fusion Generator Factory": "Fusionsgenerator-Fabrik",
  "Turbine Factory": "Turbinen-Fabrik",
  "Tesla Coil Factory": "Teslaspulen-Fabrik",
  "Medical Supplies Factory": "Medizingüter-Fabrik",
  "Satellite Factory": "Satelliten-Fabrik",
  "Drill Factory": "Bohrer-Fabrik",
  "Teleporter Factory": "Teleporter-Fabrik",
  "Wheat Farm": "Weizenfarm",
  "Corn Farm": "Maisfarm",
  "Cocoa Bean Farm": "Kakaobohnenfarm",
  "Coffee Bean Farm": "Kaffeebohnenfarm",
  "Tea Plantation": "Teeplantage",
  "Spice Farm": "Gewürzfarm",
  "Potato Farm": "Kartoffelfarm",
  "Vegetable Farm": "Gemüsefarm",
  "Fruit Farm": "Obstfarm",
  "Rice Farm": "Reisfarm",
  "Sheep Ranch": "Schafranch",
  "Cattle Ranch": "Rinderranch",
  "Fish Farm": "Fischfarm",
  "Dairy Farm": "Milchfarm",
  "Brewery": "Brauerei",
  "Vineyard": "Weingut",
  "Distillery": "Destillerie",
  "Nutrient Extract Manufactory": "Nährstoffextrakt-Manufaktur",
  "Food Bar Factory": "Nahrungsriegel-Fabrik",
  "Luxury Food Factory": "Luxusnahrungs-Fabrik",
  "Water Facility": "Wasseranlage",
  "Silicon Mine": "Siliziummine",
  "Ore Mine": "Erzmine",
  "Coal Mine": "Kohlemine",
  "Oil Rig": "Ölbohrinsel",
  "Noble Metal Mine GP": "Edelmetallmine (Gold/Platin)",
  "Noble Metal Mine SP": "Edelmetallmine (Silber/Platin)",
  "Noble Metal Mine SG": "Edelmetallmine (Silber/Gold)",
  "Zinc Mine": "Zinkmine",
  "Copper Mine": "Kupfermine",
  "Lead Mine": "Bleimine",
  "Aluminum Mine": "Aluminiummine",
  "Ice Mine": "Eismine"
};

// Generate translations.ts
const i18nCode = `export const deTranslations: Record<string, string> = ${JSON.stringify(deDict, null, 2)};

export const t = (key: string, lang: 'en' | 'de') => {
  if (lang === 'en') return key;
  return deTranslations[key] || key;
};
`;
fs.writeFileSync('src/data/translations.ts', i18nCode);

// Insert missing mines
factories.push(
  { id: "silicon_mine", name: "Silicon Mine", inputs: [], outputs: ["Silicon"] },
  { id: "ore_mine", name: "Ore Mine", inputs: [], outputs: ["Ore"] },
  { id: "coal_mine", name: "Coal Mine", inputs: [], outputs: ["Coal"] },
  { id: "oil_rig", name: "Oil Rig", inputs: [], outputs: ["Raw Oil"] },
  { id: "noble_metal_mine_gp", name: "Noble Metal Mine GP", inputs: [], outputs: ["Gold", "Platinum"] },
  { id: "noble_metal_mine_sp", name: "Noble Metal Mine SP", inputs: [], outputs: ["Silver", "Platinum"] },
  { id: "noble_metal_mine_sg", name: "Noble Metal Mine SG", inputs: [], outputs: ["Silver", "Gold"] },
  { id: "zinc_mine", name: "Zinc Mine", inputs: [], outputs: ["Zinc"] },
  { id: "copper_mine", name: "Copper Mine", inputs: [], outputs: ["Copper"] },
  { id: "lead_mine", name: "Lead Mine", inputs: [], outputs: ["Lead"] },
  { id: "aluminum_mine", name: "Aluminum Mine", inputs: [], outputs: ["Aluminum"] },
  { id: "ice_mine", name: "Ice Mine", inputs: [], outputs: ["Water"] }
);

const engFactories = factories.map(f => {
  let mappedInputs = f.inputs;
  
  if (f.id === 'carbon_extractor') {
      mappedInputs = [ ["Corn", "Wheat", "Potatoes"] ];
  }
  
  return {
    id: f.id,
    name: f.name,
    inputs: mappedInputs,
    outputs: f.outputs,
    color: '#' + Math.floor((Math.abs(f.id.split('').reduce((a,b)=>{a=((a<<5)-a)+b.charCodeAt(0);return a&a},0)) % 16777215)).toString(16).padStart(6, '0')
  };
});

const tsCode = `export type FactoryData = {
  id: string;
  name: string;
  inputs: (string | string[])[];
  outputs: string[];
  color: string;
};

export const factories: FactoryData[] = ${JSON.stringify(engFactories, null, 2)};
`;

fs.writeFileSync('src/data/factories.ts', tsCode);
console.log('Generated src/data/translations.ts and src/data/factories.ts');
